### ISSUE TITLE
Enable the nice GDI+ drawing for XE4+

### ISSUE THREAD

**Issue by edwinyzh** [EtheaDev/IconFontsImageList#11]
First, I really appreciate your great work! It's really useful for our Delphi developers to make our software to adapt HD screenshots available everywhere!

According to [the GDI/GDI+ wiki page](https://github.com/EtheaDev/IconFontsImageList/wiki/GDI), you enable GDI+ drawing for XE6+, but actually at least XE4 already support GDI+

I've made the changes (very little) and successfully compiled it. I'm about to make a PR, but due to national network issue here, I'll have to do it a little later.

**Comment by carloBarazzetta** [comment]
Well done, I haven't XE4 so I cannot test it with this version. I'm awaiting your PR.
Thanks.

**Comment by edwinyzh** [comment]
I'm still resolving my GFW-related issue (never mind if you don't know what is it)

Actually there are only two changes I made:
IconFontsImageList.inc:
```
{$IFDEF DXE4+}
  {$Define GDI+}
{$ENDIF}

```

Line 228 of IconFontsImage.pas, TIconFontImage.Paint.CalcWidth:
Change
`      {$IFDEF XE8+}`
to:
`      {$IFDEF GDI+}`

Although with these changes I can **build** the demo, and at **runtime** it seems to be drawing the icons with anti-aliasing GDI+, but at **designtime** in the IDE I couldn't add my desired icons to a TFontIconImageList, because all icons are being displayed as **squares**, as shown in the attached screenshot below, any ideas as to how to solve it? Thanks!
![FontIconImageList error under xe4](https://user-images.githubusercontent.com/541197/88565384-1920a480-d067-11ea-9170-2bfc4646bd82.png)

**Comment by carloBarazzetta** [comment]
It's very strange because the demo launches the same Editor showed by the IDE.
Are you sure the design-time package was rebuilt and reinstalled?

**Comment by edwinyzh** [comment]
@carloBarazzetta, it was late last night, maybe I missed something, anyway, I re-built and re-installed the package again, and now the designtime icon editor works!

**Comment by edwinyzh** [comment]
I'm upgrading my git in order to solve the clone and push issues. I'll make a PR once I get the network/git resolved.

**Comment by edwinyzh** [comment]
PR #13 created

**Comment by carloBarazzetta** [comment]
PR accepted
