### ISSUE TITLE
[RAD Studio 20.3] Unexpected memory leak warning after run demo project

### ISSUE THREAD

**Issue by rubemrocha** [EtheaDev/IconFontsImageList#14]
**Describe the bug**
When you run the demo project through the Delphi IDE, and after changing the UI theme, an unexpected memory leak message appears.

**To Reproduce**
1. Open the demo project in Delphi IDE (in my case, RAD Studio 10.3)
2. Change the theme for different options '....'
3. Close the UI

**Expected behavior**
The unexpected memory leak message appears before the application is terminated.

**Screenshots**
![image](https://user-images.githubusercontent.com/4088716/89114639-d2f38880-d44c-11ea-83ca-8f293701f528.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional
 - RAD Studio 10.3
 - Intel I3 Processor / 4GB RAM / 120 SSD HD

**Comment by carloBarazzetta** [comment]
It seems a memory-leaked caused by changing the VCLStyle and the TTreeView component, not caused by my components.

**Comment by carloBarazzetta** [comment]
This problem is not caused by the IconFontsImageList components.
