### ISSUE TITLE
Empty SaveToFile

### ISSUE THREAD

**Issue by SoyYako** [EtheaDev/IconFontsImageList#15]
Hi,
Metohod IconFontsImageList.SaveToFile('list.bmp'); create a empty image.

IconFontsImageList.SaveToFile('list.bmp'); create a empty BMP file.
IconFontsImageList.SaveToFile('list.png'); create a empty PNG file.

How to strore / reload a icon's list into a image file?

***********
Delphi XE 10.3
Windows 10

**Comment by carloBarazzetta** [comment]
Yes, this is a bug...

**Comment by SoyYako** [comment]
... and "Export" command from the CharMap, all icons or single icon.

**Comment by carloBarazzetta** [comment]
> ... and "Export" command from the CharMap, all icons or single icon.

Using the custom "CharMap" you can select multiple icons with Ctrl+click to "importo" into ImageCollection.
In the folder IconFontsImageList\Demo\Fonts you can find cheatsheet.html, a useful preview of the material icons.
