### ISSUE TITLE
The 'Font "Material Design Icons Desktop" is not installed' issue

### ISSUE THREAD

**Issue by edwinyzh** [EtheaDev/IconFontsImageList#17]
This might/might not an issue of IconFontsImageList, however, it's relevant so at least worth a discussion here and thus benefit all others that might encounter the same issue.

I use Inno Setup to install the font for the end users, the code is a variant of the following:
`Source: D:\Project1\Fonts\Material Design Icons Desktop.ttf; DestDir: {fonts}; FontInstall: Material Design Icons Desktop; Flags: uninsneveruninstall onlyifdoesntexist
`

I believe the font installed correctly on most of the computers, but it seems to be failed on some of them because my program that uses the font reported the issue stated in the title.

Have you encountered this and do you have any idea? Thanks!

**Comment by carloBarazzetta** [comment]
The message "The Font "Material Design Icons Desktop" is not installed" is raised if Screen.Fonts.IndexOf(AFontName) = -1 
I don't know why...
You can also install the font "on-the-fly" at application startup, using OnFontMissingEvent as you can see in the demo project in TMainForm procedure IconFontsImageListFontMissing.

**Comment by edwinyzh** [comment]
@carloBarazzetta,

I'm not sure if installing the font using `AddFontResource` on-the-fly works, according to [this post](https://stackoverflow.com/a/59112398/133516), all font is installed through `AddFontResource` so I assume so does Inno Setup.

The issue might has something to do with permissions and the Windows Firewall:
[Can't Install ANY Fonts on Windows 10](https://answers.microsoft.com/en-us/windows/forum/windows_10-files/cant-install-any-fonts-in-windows-10/b11a1ac3-ddc9-4980-9d0e-5c501ab08749?auth=1)

**Comment by carloBarazzetta** [comment]
The post explain how to install fonts in system folder SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts.
the demo installs the font "on-the-fly" without storing the file in the system folder, because is not necessary.
Try to deploy the demo ("Bin" and "Fonts" folder) on the computer that fails the font installation, to try and check if you can resolve the issue.

**Comment by limelect** [comment]
I changed to Material Design Icons and it workes

**Comment by carloBarazzetta** [comment]
> I changed to Material Design Icons and it workes

Are you using the old ttf font "materialdesignicons-webfont.ttf"?
Take care of [this](https://github.com/EtheaDev/IconFontsImageList/wiki/Deploy-Applications):

**Comment by edwinyzh** [comment]
> I changed to Material Design Icons and it workes

Do you mean you have the same issue with "Material Design Icons Desktop" but not "Material Design Icons"?
