### ISSUE TITLE
difficult to understand how to use it

### ISSUE THREAD

**Issue by AdminUser0** [EtheaDev/IconFontsImageList#19]
Hi
The documentation lacks. 
I tried to do what seems to be a simple task:
I have an action list and I want to assign icons to those actions. 
This controls seemed to be what I need but I cannot figure out how to use it.

For example, I see a certain Unicode chat that I want to use. But I cannot add it to the imagelist.

**Comment by carloBarazzetta** [comment]
Hi, there is a complete [Wiki section](https://github.com/EtheaDev/IconFontsImageList/wiki/Index) and a complete [demo](https://github.com/EtheaDev/IconFontsImageList/wiki/Demo-(VCL)) in the project that uses an ActionList.
Remember to install the font "Material Design Icons Desktop.ttf" provided into .\IconFontsImageList\Demo\Fonts folder.
