### ISSUE TITLE
Save icon

### ISSUE THREAD

**Issue by limelect** [EtheaDev/IconFontsImageList#2]
1. trying to understand how a number result in an icon - ok i got it
2. It would have been nice if you can SAVE an icon as a png or bmp to a directory
3 the max is  2990 ?

**Comment by carloBarazzetta** [comment]
The philosofy under IconFontsImageList is to use icons built from fonts, so you can resize and repaint them with different colors... Why do you need to save icon as png or bmp?
Anyway you ca do it at run-time using methods of ImageList class, the ancerstor class of IconFontsImageList, so write your own utility starting with the demo project to save icons in any image format.
