### ISSUE TITLE
Suggestion for icon editor - allow pasting color values such as $00317eff

### ISSUE THREAD

**Issue by edwinyzh** [EtheaDev/IconFontsImageList#21]
It'll be very handy if we can directly pasting color values such as $00317eff when editing icons in the icon editor.

**Comment by carloBarazzetta** [comment]
Use the "structure editor" to select your item and paste the color value directly into Object Inspector:
![image](https://user-images.githubusercontent.com/7803548/90106097-3af87780-dd47-11ea-95da-716f08612421.png)
Or add a popup menu to any color-box in the component editor ad make a "pull-request" of your changes.
The source code is open!

**Comment by edwinyzh** [comment]
Excellent! That works!
