### ISSUE TITLE
The icons that are stored in IconFontList are static?

### ISSUE THREAD

**Issue by SoyYako** [EtheaDev/IconFontsImageList#22]
After loading multiple IconsFont into the list at design time...
Do the icons remain as iamges within the list? ... or only pointers / references to certain Fonts.

Basically the question is:
When I run "my program" on the target PC, do the images persist even though the "Material Font" is not installed?

Best regards,

**Comment by carloBarazzetta** [comment]
The font is necessary to "build" (draw) the icon at any resolution or color, so you "must" deploy the font when you deploy your application, as explained here:
https://github.com/EtheaDev/IconFontsImageList/wiki/Deploy-Applications
