### ISSUE TITLE
Editor does not show correctly the icons

### ISSUE THREAD

**Issue by limelect** [EtheaDev/IconFontsImageList#25]
D10.2.3
In the editor, the chosen icon property is shown but for example, $F0e5c is square in the editor.
Last download
![Screenshot - 22_08_2020 , 16_05_33](https://user-images.githubusercontent.com/4199131/90956670-5b37dd00-e491-11ea-862c-efcde31aca5b.jpg)

**Comment by carloBarazzetta** [comment]
I don't understand which font you are using because with the one present in IconFontsImageList \ Demo \ Fonts which is called "Material Design Icons Desktop.ttf" I never had any problem (in your images I see another name: "Material Design Icons").
Once installed in Windows I see all the characters both in the component editor and at run-time. Can you attach the font you are using to see if that is the problem?

**Comment by SoyYako** [comment]
Hi friends,
I had the same problem installing in the target system. When the component cannot load the font, the boxes appear.

Note that the checking routine through the "OnFntMissign" event is a very good idea, but in Delphi versions "10.nnn", it does not load the source resource well.

For it to work, the **_"Material Design Icons Desktop"_** font must be installed on the target system (as ADMIN and available to all users).

I hope it helps you. Bye!

**Comment by limelect** [comment]
I have all the needed fonts installed.
Tried both.
Material Design Icons Desktop
Material Design Icons 
Same for both

**Comment by SoyYako** [comment]
Uninstall all related fonts and re-install only "...Icons Desktop" font.
Update system... 
Update GDI+ library...
In custom new app, drop a IconFontsImageLib and try load some fonts in runtime, from system font path.

**Comment by carloBarazzetta** [comment]
Today I've pushed a new version, with big refactoring and new components...
Please test with the new version 2.2 and check if the problem persist with the new component editor.

**Comment by carloBarazzetta** [comment]
Any feed-back with the new version? Now I've extended the check for font missing to the ImageCollection and fix the demo.

**Comment by carloBarazzetta** [comment]
Any comment @limelect or @SoyYako ?

**Comment by SoyYako** [comment]
Ok, lets go...
this new release allow export images?

**Comment by carloBarazzetta** [comment]
No, but I don't know why do you need an export function... what is the purpose?

**Comment by carloBarazzetta** [comment]
Export icons into png files was implemented.

**Comment by SoyYako** [comment]
Thanks Carlo, 
I have not been able to update the library for work reasons. 
On weekends I use them to do these tasks...
Until next time!
