### ISSUE TITLE
[Question]No need to use TVirtualImageList since we can already set the size of TIconFontsImageList?

### ISSUE THREAD

**Issue by edwinyzh** [EtheaDev/IconFontsImageList#26]
I noticed the recent addition of TVirtualImageList. If I understand it correctly, the only purpose of TVirtualImageList is to produce variant sizes of icon. But since we can already change the width/height of TIconFontsImageList and it will regenerate the bitmap of the new size, and this is already really well in my project. I think there is no need to use TVirtualImageList at all?

Please correct me if I'm wrong.

**Comment by carloBarazzetta** [comment]
If you have an application with only one form you can continue to use the classic TIconFontsImageList: loading the form, it generates all the icons you need, and when you change monitor / DPI the icons are resized.
But if you have two forms in an environment with 2 monitors with different DPI, if you use only one imagelist, when the second form requires icons of different sizes the imagelist regenerates all the bitmaps, notify who is using them, then the size of the icons change also on the other form, on the first monitor.
using TIconFontsImageCollection you can centralize your icon collection in a shared datamodule (without defining a Size) and put a TIconFontsVirtualImageList (or a TVirtualImageList if you have Delphi 10.3 or later) defining the size. When the second module switches to another monitor, only VirtualImageList in these modules requires resizing of the icon.
Another advantage is to use a single ImageCollection with two imagelist on the same form (eg. 16 px on toolbar and 24 px on buttons...).

**Comment by edwinyzh** [comment]
@carloBarazzetta, thanks for the explanation!
