### ISSUE TITLE
Re-install

### ISSUE THREAD

**Issue by SoyYako** [EtheaDev/IconFontsImageList#28]
Hi Carlo, sorry....
First;
In the Wiki dont see...
how un-install old library and re-install new package?

Second;
what is the difference between web and desktop fonts  TTF files?

Third;
do I need to have both TTF fonts installed to program code?
in my clients, I have only installed "xxDesktop.ttf" because I only need the images contained there....

As usual, thanks for your kind answers.
-YAKO-

**Comment by carloBarazzetta** [comment]
First:
Uninstall old packages from menu Components/InstallPackages as usual, but normally I reopen package group and rebuild all, without need to uninstall packages.
Second:
I don't understand: you can use different fonts with the components, for example you can use the font "Material Design Icons Desktop.ttf" stored into IconFontsImageList\Demo\Fonts that have a nice preview tool (opening cheatsheet.html), but you can also use any other ttf font file, for example the ones here: https://www.fontsquirrel.com/fonts/list/tag/icons
You can setup "Material Design Icons Desktop" as the main font of the collection (so you don't need to specify on any item) and you can define other icons taken from other fonts (you must specify FontName into specific items)...

Third:
The ONLY font that you need in your machine and on target machine is the font that you are using: if you are using only one font you need to deploy only one font...

**Comment by SoyYako** [comment]
Thanks Carlos,
In first point, i serach fror "InconFonts..." package, and them is "Ethera..." name... sorry.
In point 2 & 3, I understand that "xxxWEB.ttf" is for FMX projects, and "xxxDesktop.ttf" for VCL... in my case, I only care about VCL, so this would be fine only with "xxxDesktop.ttf".
Thanks again,
