### ISSUE TITLE
Ver 2.2.2 compile error

### ISSUE THREAD

**Issue by SoyYako** [EtheaDev/IconFontsImageList#30]
In version 2.2.2, don't compile...
Message error is:
[dcc64 Error] IconFontsImageListBase.pas(745): E2003 Undeclared identifier: 'SaveToPngFiles'

function TIconFontsImageListBase.SaveToPngFiles(const AOutFolder: string): Integer;
begin
  {$IFDEF UNICODE}
  Result := IconFontsUtils.SaveToPngFiles(Self, AOutFolder);  ///<<<<< error line
  {$ELSE}
  Result := 0;            
  {$ENDIF}
end;

------------------------
Delphi VCL 10.3
Win 10

**Comment by carloBarazzetta** [comment]
Fixed now.

**Comment by SoyYako** [comment]
Thanks Carlo, you are a genius!
