### ISSUE TITLE
Images not exported

### ISSUE THREAD

**Issue by SoyYako** [EtheaDev/IconFontsImageList#31]
In version 2.2.2, the "Export" option from de Editor, only export icon named.

My IconList have 250 icons, but only 43 were exported.
More, the "first" imege export has named **".png"** , no name, only extension.
This image is the last image in the list.
I have no more data to provide ...

In addition to the icon names ...
Using the **"Custom Charmap"**, it is possible select icons (preloaded from the "xxxDesktop.ttf" font).
The preload, retrieves the names of the icons and their Hex value.

When an icon is selected (copied) to the **IconFontsList**, the Hex value is retrieved, but not the name.

It is not important, it is just a visual matter.... but...
If to export a name is required, then if it becomes something important.
Another possibility is that, when exporting images, if the icon does not have a name, its position **Idx** is assigned as a name, like "idx_1.png"; "or "365.png"
it's an idea...

**Comment by carloBarazzetta** [comment]
Fixed now: filenames now contains IconName or Index +(HexValue) of the Icon.

**Comment by SoyYako** [comment]
Thanks Carlo, you are very fast!  :-D
