### ISSUE TITLE
Ver 2.2.2. - New features

### ISSUE THREAD

**Issue by SoyYako** [EtheaDev/IconFontsImageList#32]
Marco, 
Today I'm upset, but I really want to help...

On the home page, it reads: "We recommend that TIconFontsVirtualImageList be used only for Delphi versions prior to 10.3 ....", but the DEMO 10.3 uses it.

What is better in the future?
If TIconFontsVirtualImageList tends to disappear, better to start with the native component TVirtualImageList.
Don't you think?

Another point says: "Don't forget also the importance of PreserveItems ...."
Where is this option?
It is not among the TIconFontsImageList component properties; or in TIconFontsImageCollection; or in TIconFontsVirtualImageList ...?

**Comment by carloBarazzetta** [comment]
Yes, the future is using TVirtualImageList instead of TIconFontsVirtualImageList.
PreserveItems is a property of TVirtualImageList, and is one of the important feature that TIconFontsVirtualImageList don't have.
If you have TVirtualImageList use it in your application.
Carlo

**Comment by carloBarazzetta** [comment]
Hi @SoyYako : I've pushed a new version 2.3 with **complete** support for VirtualImageList.
The demos for D10.3 and D10.4 are updated with a new UMainFormNew.pas/dfm that uses a TVirtualmageList.
Please give me a feed-back!
Thanks.

**Comment by SoyYako** [comment]
Perfect! Thanks"
