### ISSUE TITLE
Move/import images

### ISSUE THREAD

**Issue by SoyYako** [EtheaDev/IconFontsImageList#34]
Hi friends,
How move images from TIconFontsImageList to new TIconFontsImageCollection?

**Comment by carloBarazzetta** [comment]
Manually from dfm: copy and paste.

**Comment by SoyYako** [comment]
Chiao Carlo...
not sure how to do this...
which part should I copy and paste?

**Comment by carloBarazzetta** [comment]
Copy:
```
    IconFontItems = <
      item
        FontIconDec = 983041
      end
    ....
   end>
```
form a component to another...

**Comment by SoyYako** [comment]
Genius!
Perfect, I'll try later
