### ISSUE TITLE
Ghost component  :-D

### ISSUE THREAD

**Issue by SoyYako** [EtheaDev/IconFontsImageList#35]
Hi...
In new DEMO 2.3, have a next line on Form Create method:
`  FIconFontsVirtualImageListHot := TIconFontsVirtualImageList.Create(Self)`
which is dynamically created, but then doesn't seem to be used/assigned in any component/process.

Anyway, the **TopToolBar** component, still shows the "Hot" effect.

So, it is no longer necessary to use a second component in runtime?

**Comment by carloBarazzetta** [comment]
yes, it's an old line of code...
