### ISSUE TITLE
package 'dclfmxstd' not found

### ISSUE THREAD

**Issue by genna80** [EtheaDev/IconFontsImageList#40]
**Describe the bug**
Hi, when i Try to compile All your component on D 10.3.2 i obtain this error msg:
[dcc32 Fatal Error] dclIconFontsImageListFMX.dpk(36): E2202 Required package 'dclfmxstd' not found
I can risolve this error ?
Thanks

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by carloBarazzetta** [comment]
the file is present here:
{yourfolder}\IconFontsImageList\Packages\D10_3
You've opened:
{yourfolder}\IconFontsImageList\Packages\D10_3\IconFontsImageGroupPackages.groupproj
And build all projects inside it?
![image](https://user-images.githubusercontent.com/7803548/102225201-37d4ea00-3ee7-11eb-8221-25d793b692ff.png)

**Comment by carloBarazzetta** [comment]
Sorry, I haven't notice that the error is: "Required package 'dclfmxstd'" not found!
Probably you dont haveFiremonkey platform, so you don't need to build IconFontsImageListFMX and dclIconFontsImageListFMX packages, but only the two VCL packages!

**Comment by genna80** [comment]
Sorry but i have fmx platform. I haven't or not found that library

**Comment by carloBarazzetta** [comment]
I'm using Delphi 10.3 update 3, and dclfmxstd is a Delphi desing-time package for propertyeditors.
Probably is not present in 10.3.2.
In 10.3.3 it's necessary only for FmxAnimationEditors unit, so you can remove this required package from contains section and remove all the property-editor registrations.... or upgrade to 10.3.3!

**Comment by genna80** [comment]
Thanks. I remove this required package.
