### ISSUE TITLE
Some icons are not shown

### ISSUE THREAD

**Issue by edwinyzh** [EtheaDev/IconFontsImageList#42]
I've encounter several icons that couldn't be displayed correctly by the image list, and today I encountered another:  F15AB: list-status, as shown in the attached screenshot.

Please advise how to solve it. 

Love this excellent lib, BTW :)

![some material desktop icons not shown](https://user-images.githubusercontent.com/541197/109153624-1bd3ab80-77a8-11eb-9b23-3ce8e64c1bd4.png)

**Comment by carloBarazzetta** [comment]
Are you sure that the font installed on your system is the same version you are looking at in the documentation? I believe they are recently added icons that you don't see because the ttf file is out of date.

**Comment by edwinyzh** [comment]
@carloBarazzetta , you are right! Re-installed the ttf font file, restarted the Delphi IDE and it works!

Thank you!

**Comment by edwinyzh** [comment]
x
