### ISSUE TITLE
Error compiling FMX design time package with 10.3

### ISSUE THREAD

**Issue by Daniela-Zanini** [EtheaDev/IconFontsImageList#44]
Hi Carlo, we just tried to install IconFontImageList on a 10.3 Delphi installation but it fails with the following error:

[dcc32 Fatal Error] dclIconFontsImageListFMX.dpk(36): E2202 Required package 'dclfmxstd' not found

We are addressing VCL application at the moment so we just skipped it but zou may be interested in fixing this nonetheless.
Thanks

**Comment by carloBarazzetta** [comment]
Hi Daniela, thank you for the warning. Did you download the library from GetIt or from this GitHub repository?
