### ISSUE TITLE
Search for icon name in Icon Fonts Charmap

### ISSUE THREAD

**Issue by DiegoArnaudin** [EtheaDev/IconFontsImageList#45]
Search for icon name in Icon Fonts Charmap

**Comment by DiegoArnaudin** [comment]
It would be very useful to be able to search an icon for its iconName

**Comment by carloBarazzetta** [comment]
A simple way to search icons for example of Material Design Fonts is to use the file: IconFontsImageList\Demo\Fonts\cheatsheet.html.
In the library there is a "catalog" support only for MaterialDesign  (Icons.MaterialDesign.pas) that give you some the name of the icon (as you can see in the charmap) but there isn't a search/filter option into this form.
You can do it by yourself changing the unit IconFontsCharMapUnit.pas
![image](https://user-images.githubusercontent.com/7803548/120172673-9545c480-c203-11eb-9bd2-940e30b1586c.png)

**Comment by DiegoArnaudin** [comment]
thats why ive submited this issue duh...
It was like saying: how good it would be if you could search... 
it doesn't matter, thanks anyway
