### ISSUE TITLE
Segmentation Fault in Android

### ISSUE THREAD

**Issue by MarkBracey** [EtheaDev/IconFontsImageList#46]
I can't really (yet) give you a way to duplicate the problem.

I only see this issue in Android, mostly in Android 11

I'm using IconFontImageList extensively in my Android App.  I see the issue when I change tabs using
 TabControl.SetActiveTabWithTransitionAsync(ActiveTab,TTabTransition.Slide, Direction, AfterOpen);

And the page I am tabbing from has a lot of images on them.

Basically I'm just getting a Segmentation Fault on what appears to be a memory move.

I've attached a screenshot of the call stack.  I will try to reproduce this in a smaller app but I am posting this in case this is an issue you are already familiar with.

![image](https://user-images.githubusercontent.com/13353979/128429828-4dd16c63-8afd-489c-8065-81abed42b6ac.png)

**Comment by carloBarazzetta** [comment]
I'm sorry but I don't have a lot of experience with Android and I can't help you in this specific case. Most of the tests I did with FMX/Windows.

**Comment by carloBarazzetta** [comment]
No feedback, issue closed.
