### ISSUE TITLE
Installation: File not found: 'FMX.IconFontsImageListEditorUnit.fmx'

### ISSUE THREAD

**Issue by TCardinal** [EtheaDev/IconFontsImageList#5]
Unable to install dclIconFontsImageListFMX_10_3.bpl because FMX.IconFontsImageListEditorUnit.fmx' is missing

**To Reproduce**
Attempt to install dclIconFontsImageListFMX_10_3.bpl after building IconFontsImageListFMX_10_3.bpl

**Expected behavior**
Package would be installed

Using Delphi 10.3
Windows 10

**Comment by carloBarazzetta** [comment]
Donwload official release 1.7 VCL and 1.1 FMX now, it was fixed!

**Comment by carloBarazzetta** [comment]
Sorry, it was included now in the official release.

**Comment by carloBarazzetta** [comment]
Thank you for your feed-back!
