### ISSUE TITLE
Don't auto-switch to dark mode

### ISSUE THREAD

**Issue by SoyYako** [EtheaDev/IconFontsImageList#52]
Hello friends,
First step: sorry for my poor English.

I am upgrading the component from 2.3 to **3.3.1** version.

But this version, activates an **"Auto-Switch"** to dark mode if my IDE is also dark mode.
In this mode, the icons (all in clBlcak color) are blurred or at least not displayed comfortably.

So... 
How to change or disable that auto-switch and go back to clear mode (an original)?

Certainly, the IDE will remain dark, but the Editor needs to remain in light (normal) mode.

Best regard,
Yako

**Comment by carloBarazzetta** [comment]
If you are using this repo (not GetIt) and you can rebuild packages, try to remove those lines into IconFontsImageListEditorUnit.pas:
    if ThemeProperties <> nil then
    begin
      LStyle := ThemeProperties.StyleServices;
      StyleElements := StyleElements - [seClient];
      Color := LStyle.GetSystemColor(clWindow);
      BottomPanel.StyleElements := BottomPanel.StyleElements - [seClient];
      BottomPanel.ParentBackground := False;
      BottomPanel.Color := LStyle.GetSystemColor(clBtnFace);
      IDEThemeManager.RegisterFormClass(TIconFontsImageListEditor);
      ThemeProperties.ApplyTheme(Self);
    end;
