### ISSUE TITLE
Icons are trimmed

### ISSUE THREAD

**Issue by urlept** [EtheaDev/IconFontsImageList#6]
![ice_screenshot_20200516-162540](https://user-images.githubusercontent.com/15120058/82122451-0d298400-9794-11ea-9851-b4a70d6625a7.png)
![ice_screenshot_20200516-162621](https://user-images.githubusercontent.com/15120058/82122454-1155a180-9794-11ea-8049-d3dca54895d5.png)

Icon 'download' from FontAwesome is trimmed.
It does not appear fully in Icon Fonts ImageList Editor.
Also does not apper fully in delphi project.
Same with icon 'upload' and many others.

Congratulation for this nice utility.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox
 - Version 76.0.1

**Comment by carloBarazzetta** [comment]
Probably Icons have not a "square" dimension. I'm working to expand Width and Height properties for ImageList so you can set the correct sizes.

**Comment by carloBarazzetta** [comment]
In 2.0 version you can specify also "With" and "Height" properties, insted of "Size", so you can have icons larger and probably resolve this problem.
2.0 supports GDI+
