### ISSUE TITLE
ModernAppDemo not run

### ISSUE THREAD

**Issue by allancmello** [EtheaDev/IconFontsImageList#7]
The application not compile. Message error:
**[dcc32 Error] E1026 File not found: 'AwesomeFont.RES'**

**Desktop:**
 - OS: Windows 
 - Version 10

**Comment by carloBarazzetta** [comment]
Retry with latest version committed.

**Comment by allancmello** [comment]
Hi Carlo, 
I´m try the new latest version, but, isnt run. 
**File 'Awesome Font.RES' is missing**
Look the picture bellow.

![image](https://user-images.githubusercontent.com/1229105/84648519-87f0d680-aedb-11ea-9fcb-05f8cfe355b7.png)

My is RAD Studio 10.3.3

**Comment by carloBarazzetta** [comment]
Oh, yes, it's a resource file used by VCLStyleUtils library that the demo uses if you compile with VCLSTYLEUTILS directive.
Now the file is present into the repo, please give me a feed-back if you can compile it now!

**Comment by allancmello** [comment]
Yes my dear, now everything works perfectly. 
Thanks!

**Comment by carloBarazzetta** [comment]
Perfect. bye.
