### ISSUE TITLE
ERRORE APPLY BUTTON

### ISSUE THREAD

**Issue by pylot66** [EtheaDev/IconFontsImageList#9]
Nella modifica delle caratteristiche delle icone, l’editor integrato mi segnala " ACCESS VIOLATION " se clicco sul tasto APPLY. 
Uso windows 10 build 2004 e Delphi 10.3 comunity edition.
Enrico Pilotto
![errore1](https://user-images.githubusercontent.com/28526774/85021507-3b72f880-b172-11ea-82b0-e7ee5a52fe11.jpg)

**Comment by carloBarazzetta** [comment]
Resolved in version 2.0
